import { readPartner } from '@/lib/controllers'
import Head from 'next/head'
import Image from 'next/image'
import logo from '../assets/logo.svg'

/**
 * server side
 * @param {*} context 
 * @returns 
 */
export async function getServerSideProps(context) {
  const response = await readPartner()
  const data = await response

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }

}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Talk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <header className='d-flex justify-content-center py-3'>
          <figure>
            <Image src={logo} width='32' height='32' alt='talk'></Image>
            <button type="button" class="position-relative">
              Talkers
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                {data.length}+
                <span class="visually-hidden">unread messages</span>
              </span>
            </button>
          </figure>
        </header>
      </main>
    </>
  )
}
