import Head from 'next/head'
import Image from 'next/image'
import logo from '../assets/logo.svg'
export default function Home() {
  return (
    <>
      <Head>
        <title>Talk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <figure>
          <Image src={logo} width='32' height='32' alt='talk'></Image>
          Talk
        </figure>
      </main>
    </>
  )
}
